# Generated by Django 6.0.5 on 2026-05-16 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación')], max_length=15, verbose_name='Acción')),
                ('registro_id', models.IntegerField(verbose_name='ID del Registro afectado')),
                ('datos_anteriores', models.TextField(blank=True, null=True, verbose_name='Datos Antes del Cambio')),
                ('datos_nuevos', models.TextField(blank=True, null=True, verbose_name='Datos Después del Cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora Exacta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor')),
            ],
            options={
                'verbose_name': 'Historial de Auditoría',
                'verbose_name_plural': 'Historial de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
