# Generated by Django 6.0.5 on 2026-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historialregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes (1-12)')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('objetivo_ingresos', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Objetivo Ingresos (DH)')),
                ('limite_gastos', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12, verbose_name='Límite Máximo Gastos (DH)')),
            ],
            options={
                'verbose_name': 'Meta Financiera',
                'verbose_name_plural': 'Metas Financieras',
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
